/// Flutter icons Epilexa
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Epilexa
///      fonts:
///       - asset: fonts/Epilexa.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Epilexa {
  Epilexa._();

  static const _kFontFam = 'Epilexa';
  static const _kFontPkg = null;

  static const IconData vectorprofile = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vectorheart = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vectortemp = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
